# Generated by Django 5.2.7 on 2025-11-12 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(
                null=True,  # allow null temporarily to avoid default issues
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(
                    choices=[
                        ('TERM1', 'First Term'),
                        ('TERM2', 'Second Term'),
                        ('TERM3', 'Third Term')
                    ],
                    max_length=20
                )),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_position', models.IntegerField()),
                ('overall_grade', models.CharField(max_length=1)),
                ('teacher_remarks', models.TextField()),
                ('principal_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
