# Generated by Django 5.2.7 on 2025-11-14 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_timetable_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='BORROWED', max_length=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='core.student')),
            ],
            options={
                'verbose_name': 'Book Loan',
                'verbose_name_plural': 'Book Loans',
                'ordering': ['-borrowed_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_periods', models.IntegerField(default=5)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Class Subject Allocation',
                'verbose_name_plural': 'Class Subject Allocations',
                'ordering': ['class_level', 'section', 'subject__name'],
                'unique_together': {('class_level', 'section', 'subject', 'academic_year')},
            },
        ),
    ]
