# Generated by Django 5.2.7 on 2025-12-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookloan_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionhistory',
            name='promotion_type',
            field=models.CharField(choices=[('manual', 'Manual Promotion'), ('auto', 'Automatic Promotion')], default='manual', max_length=10),
        ),
    ]
