# Generated by Django 5.2.7 on 2025-11-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exam_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='class_name',
            new_name='class_level',
        ),
    ]
