# Generated by Django 5.2.7 on 2025-11-06 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notice_options_notice_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Expense Name')),
                ('expense_id', models.CharField(max_length=50, unique=True, verbose_name='Expense ID')),
                ('expense_type', models.CharField(choices=[('salary', 'Salary'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('purchase', 'Purchase'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('due', 'Due'), ('others', 'Others')], default='pending', max_length=20, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Expense Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['expense_type'], name='core_expens_expense_75b821_idx'), models.Index(fields=['status'], name='core_expens_status_32e345_idx'), models.Index(fields=['date'], name='core_expens_date_d957f6_idx')],
            },
        ),
    ]
