# Generated by Django 5.2.7 on 2025-11-12 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_class_name_exam_class_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-marks_obtained']},
        ),
        migrations.AddField(
            model_name='examresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A (Excellent)'), ('B', 'B (Very Good)'), ('C', 'C (Good)'), ('D', 'D (Pass)'), ('E', 'E (Fail)'), ('F', 'F (Fail)')], max_length=1),
        ),
    ]
