# Generated by Django 5.2.7 on 2026-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admissionform_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionhistory',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='promotion_type',
            field=models.CharField(choices=[('manual', 'Manual Promotion'), ('auto', 'Automatic Promotion'), ('reversion', 'Reversion')], default='manual', max_length=10),
        ),
    ]
