# Generated by Django 5.2.7 on 2025-11-07 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fee_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['level_category', 'grade_level'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['class_name', 'name']},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='class_name',
        ),
        migrations.AddField(
            model_name='admissionform',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='grade_level',
            field=models.CharField(choices=[('PP1', 'Pre-Primary 1'), ('PP2', 'Pre-Primary 2'), ('PP3', 'Pre-Primary 3'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='level_category',
            field=models.CharField(choices=[('ECDE', 'Early Childhood Development Education'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Class Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(choices=[('ECDE', 'ECDE'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('ALL', 'All Levels')], default='PRIMARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E'), ('F', 'Section F')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'class_name')},
        ),
    ]
