# Generated by Django 5.2.7 on 2026-02-21 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promotionhistory_is_reverted_promotionhistory_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrowing',
            name='borrowed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
