# Generated by Django 5.2.7 on 2026-02-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookborrowing_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['class_level', 'section', 'day', 'start_time', 'period_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.transportroute'),
        ),
    ]
