# Generated by Django 5.2.7 on 2026-02-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_timetable_options_student_transport_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='core.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='core.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
