# Generated by Django 5.2.7 on 2025-11-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_academicyear_name_alter_class_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.academicyear'),
        ),
    ]
