# Generated by Django 5.2.8 on 2025-11-10 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_fee_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='birth_certificate_no',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='student',
        ),
        migrations.AddField(
            model_name='admissionform',
            name='admission_student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Student ID'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='approved_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_form', to='core.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='parent_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='parent_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admission_photos/'),
        ),
    ]
